# Generated by Django 5.0.3 on 2024-03-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='deathdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерти'),
        ),
    ]
