# Generated by Django 5.0.3 on 2024-03-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_deathdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='aboutAuthor',
            field=models.TextField(default=' ', verbose_name='О авторе'),
            preserve_default=False,
        ),
    ]
