# Generated by Django 5.0.3 on 2024-03-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_library_description_library_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='image',
            field=models.ImageField(upload_to='library'),
        ),
    ]
